### ISSUE TITLE
这个Python的版本是？

### ISSUE THREAD

**Issue by haiya512** [b1ngz/tencent_exmail#1]
Python的版本是2还是3？
找到原因了，现在应该是有升级了吧，我2.7.10 headers 参数报错

**Comment by b1ngz** [comment]
之前测试的是2，报错信息是什么？

写了有段时间了，可能是登陆逻辑变了

**Comment by haiya512** [comment]
@b1ngz 哈，自己已经改好了，不是你的原因，是我操作错误的原因，关注的github过多，消息没看到哈，不好意思
